### ISSUE TITLE
ISE hangs after upgrade to 4.3 from 4.1

### ISSUE THREAD

**Issue by francobutto** [SitecorePowerShell/Console#799]
This happens when running any script after said upgrade.
Below is the error from the sitecore logs:

`FATAL Uncaught TypeError: cognifide.powershell.showInfoPanel is not a function | SessionId-RequestId: fp0iimzhnvshmhygrx1kw5lo-dfa64b5817424027ac9cb0f1f4817e24 | PageUrl: http://ecosystem/sitecore/shell/Applications/PowerShell/PowerShellIse?sc_bw=1 | UserAgent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
Exception: JSNLog.Exceptions.ClientException
Message: cognifide.powershell.showInfoPanel is not a function
TypeError: cognifide.powershell.showInfoPanel is not a function 
    at eval (eval at scSitecore.process (http://ecosystem/sitecore/shell/controls/Sitecore.js:1043:11), <anonymous>:1:22) 
    at scSitecore.process (http://ecosystem/sitecore/shell/controls/Sitecore.js:1043:11) 
    at scRequest.resume (http://ecosystem/sitecore/shell/controls/Sitecore.js:1826:14) 
    at scRequest.handle (http://ecosystem/sitecore/shell/controls/Sitecore.js:1727:12) 
    at scRequest.execute (http://ecosystem/sitecore/shell/controls/Sitecore.js:1695:17) 
    at scSitecore.postRequest (http://ecosystem/sitecore/shell/controls/Sitecore.js:888:18) 
    at scSitecore.invoke (http://ecosystem/sitecore/shell/controls/Sitecore.js:449:15) 
    at HTMLAnchorElement.onclick (http://ecosystem/sitecore/shell/Applications/PowerShell/PowerShellIse?sc_bw=1:1:26)`

**Comment by AdamNaj** [comment]
Seems like similarly to issue #793 you need to purge your browser cache off of the old scripts.

A very common problem after SPE upgrades is that the Java scripts (that make ISE tick) get cached in the browser and you need to purge the browser cache to make things work again. Can you make sure that this is not the problem before we go deeper?

**Comment by francobutto** [comment]
Problem solved. Thank you very much AdamNaj!!
